name: Deploy Frontend
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: frontend

      - name: Build frontend
        run: yarn build
        working-directory: frontend
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2


      - name: Deploy to S3
        working-directory: frontend
        run: aws s3 sync dist/ s3://my-aws-demo-frontend --delete
				